### ISSUE TITLE
Incorrectly displaying "1 additional row" when showing the row number had been better

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1914]
## Description
I want to see the errored row's number when number to "additional row" is only one in a warning message.
## Steps to reproduce
1. Go to 'http://localhost:3000/organize/1/people'
2. Click on 'Create' and then click on 'Import people'
3. Upload a file that contains more than 10 rows, 9 of which contain malformed email addresses
4. Map columns for first name, last name and email address
5. Click on 'Validate'

### Expected Behaviour
Display row's number at the end instead of '...and 1 additional row' For example, ...1,2,3,4,5,6,7,8 and 9
### Actual Behaviour
displaying '...and 1 additional row' intead of showing row's number. This is silly, because it takes more space than just showing the row number. The "…and N additional rows" should only begin happening when there are more than 1 extra row.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/72ab0bab-acc0-4ec9-8808-b1dc81e4b6ac)

_Originally posted by @richardolsson in https://github.com/zetkin/app.zetkin.org/pull/1904#discussion_r1566150771_

**Comment by kizouker** [comment]
I'm on it!

**Comment by richardolsson** [comment]
@kizouker! Please hold off on this one until we have merged another feature, which contains a (potential) fix for this already.

**Comment by MarkusPettersson98** [comment]
@richardolsson What's the status on this?

**Comment by richardolsson** [comment]
Great question @MarkusPettersson98! Any chance you could try to reproduce and see if it was fixed already?

Basically, createa a file like this:

```csv
ID,EMAIL
10,notanemail
10,notanemail
10,notanemail
10,notanemail
10,notanemail
10,notanemail
10,notanemail
10,notanemail
10,notanemail
```

**Comment by jones58** [comment]
Just tried that file and it still says "1 additional row". Bug is still present.

**Comment by katjam** [comment]
@richardolsson I'm happy to have a go at this unless we think @kizouker is still planning to pick it up.
